import { GoogleGenAI, Type } from "@google/genai";

let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required.");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { captions } = req.body;
    if (!captions || !Array.isArray(captions)) {
      return res.status(400).json({ error: "No captions provided or invalid format." });
    }

    if (captions.length === 0) {
      return res.json({ captions: [] });
    }

    const client = getGeminiClient();
    const fileContent = JSON.stringify(captions, null, 2);

    const prompt = `
You are an expert video editor and copywriter. You are given a list of JSON caption segments containing timestamps (start and end in seconds) and raw text generated by speech recognition. Speech recognition text is often full of repeated words, fillers, lack of capitalisation, and grammatical errors.

Your job is to:
1. Fix all typos, grammatical mistakes, and incorrect words.
2. Remove standard verbal fillers such as "um", "uh", "ah", "like", "so", etc.
3. Enhance sentence flow and punctuation (proper capitalization, periods, question marks).
4. Do NOT change the duration, coordinates, start, or end times. Keep them exactly as is.
5. If some segments become empty because they only had filler words, keep them but set text to an empty string or merge adjacent contexts if appropriate, but keeping the array size and keys ("id", "start", "end", "text") intact.

Input data:
${fileContent}

Return the refined data in the exact same JSON format: a list of segments with keys "id", "start", "end", and "text" (with corrected text). Keep the timing structure exactly identical.
`;

    const response = await client.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              id: { type: Type.STRING },
              start: { type: Type.NUMBER },
              end: { type: Type.NUMBER },
              text: { type: Type.STRING }
            },
            required: ["id", "start", "end", "text"]
          }
        }
      }
    });

    const text = response.text || "[]";
    const refinedCaptions = JSON.parse(text);

    res.json({ captions: refinedCaptions });
  } catch (error: any) {
    console.error("Error refining captions:", error);
    res.status(500).json({ error: error.message || "Failed to refine captions" });
  }
}
