import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

// Load environment variables
dotenv.config();

// Helper to get Gemini Client lazily
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required but missing.");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: "50mb" }));

  // API Route: Refine Speech Transcripts & Captions using Gemini-3.5-flash
  app.post("/api/gemini/refine-captions", async (req, res) => {
    try {
      const { captions } = req.body;
      if (!captions || !Array.isArray(captions)) {
        return res.status(400).json({ error: "No captions provided or invalid format." });
      }

      if (captions.length === 0) {
        return res.json({ captions: [] });
      }

      const client = getGeminiClient();

      // Format current captions into readable text for Gemini
      const fileContent = JSON.stringify(captions, null, 2);

      const prompt = `
You are an expert video editor and copywriter. You are given a list of JSON caption segments containing timestamps (start and end in seconds) and raw text generated by speech recognition. Speech recognition text is often full of repeated words, fillers, lack of capitalisation, and grammatical errors.

Your job is to:
1. Fix all typos, grammatical mistakes, and incorrect words.
2. Remove standard verbal fillers such as "um", "uh", "ah", "like", "so", etc.
3. Enhance sentence flow and punctuation (proper capitalization, periods, question marks).
4. Do NOT change the duration, coordinates, start, or end times. Keep them exactly as is.
5. If some segments become empty because they only had filler words, keep them but set text to an empty string or merge adjacent contexts if appropriate, but keeping the array size and keys ("id", "start", "end", "text") intact.

Input data:
${fileContent}

Return the refined data in the exact same JSON format: a list of segments with keys "id", "start", "end", and "text" (with corrected text). Keep the timing structure exactly identical.
`;

      const response = await client.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                id: { type: Type.STRING },
                start: { type: Type.NUMBER },
                end: { type: Type.NUMBER },
                text: { type: Type.STRING }
              },
              required: ["id", "start", "end", "text"]
            }
          }
        }
      });

      const text = response.text || "[]";
      const refinedCaptions = JSON.parse(text);

      res.json({ captions: refinedCaptions });
    } catch (error: any) {
      console.error("Error refining captions with Gemini API:", error);
      res.status(500).json({ error: error.message || "Failed to refine captions" });
    }
  });

  // API Route: Summarize Video and Generate Content Assets (Chapters, Title, Descriptions)
  app.post("/api/gemini/summarize", async (req, res) => {
    try {
      const { transcripts } = req.body;
      if (!transcripts || typeof transcripts !== "string") {
        return res.status(400).json({ error: "Missing transcript text." });
      }

      const client = getGeminiClient();

      const prompt = `
You are a professional Content Creator and AI Producer. You are given a full transcript of a screen recording / video tutorial.
Your job is to read this transcript and generate a highly polished package of digital assets for this recording:

1. A catchy, clickable, and SEO-friendly Video Title (provide 3 options).
2. A structured video description (including a professional introduction, a bulleted list of key highlights, and social media hashtags).
3. A sequence of Timeline Chapters (with timestamps if available, or approximate thematic milestones, e.g., [00:00] Introduction, [01:15] Demo, etc.) based on the content flow.

Here is the full transcript:
---
${transcripts}
---

Provide the result as a styled JSON object conforming to this structure:
{
  "titles": ["Option 1", "Option 2", "Option 3"],
  "description": "Engaging description...",
  "chapters": [
    { "timestamp": "00:00", "title": "Introduction" },
    ...
  ]
}
`;

      const response = await client.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              titles: {
                type: Type.ARRAY,
                items: { type: Type.STRING }
              },
              description: { type: Type.STRING },
              chapters: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    timestamp: { type: Type.STRING },
                    title: { type: Type.STRING }
                  },
                  required: ["timestamp", "title"]
                }
              }
            },
            required: ["titles", "description", "chapters"]
          }
        }
      });

      const text = response.text || "{}";
      res.json(JSON.parse(text));
    } catch (error: any) {
      console.error("Error generating summary with Gemini API:", error);
      res.status(500).json({ error: error.message || "Failed to generate video bundle" });
    }
  });

  // Serve static files / integrate Vite
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
